Tencent:
  #  密钥可前往官网控制台 https://console.cloud.tencent.com/cam/capi 进行获取
  secretId: AKIDvqxxxx
  secretKey: veEc1xxxx
Alibaba:
  #  密钥可前往官网控制台 https://ram.console.aliyun.com/manage/ak 进行获取
  accessKeyId: LTAIxxx
  accessKeySecret: uWxxx